import 'package:bot_creator_shared/types/workflow_event_definition.dart';

class EventCatalog {
  static List<WorkflowEventDefinition> getEvents() {
    return const [
      WorkflowEventDefinition(
        category: 'core',
        event: 'ready',
        label: 'Ready',
        description: 'Contains the initial state information.',
      ),
      WorkflowEventDefinition(
        category: 'core',
        event: 'resumed',
        label: 'Resumed',
        description: 'Response to Resume.',
      ),
      WorkflowEventDefinition(
        category: 'core',
        event: 'interactionCreate',
        label: 'Interaction Create',
        description: 'User used an interaction, such as an application command.',
      ),
      WorkflowEventDefinition(
        category: 'commands',
        event: 'applicationCommandPermissionsUpdate',
        label: 'Application Command Permissions Update',
        description: 'Application command permission was updated.',
      ),
      WorkflowEventDefinition(
        category: 'automod',
        event: 'autoModerationRuleCreate',
        label: 'Auto Moderation Rule Create',
        description: 'Auto Moderation rule was created.',
      ),
      WorkflowEventDefinition(
        category: 'automod',
        event: 'autoModerationRuleUpdate',
        label: 'Auto Moderation Rule Update',
        description: 'Auto Moderation rule was updated.',
      ),
      WorkflowEventDefinition(
        category: 'automod',
        event: 'autoModerationRuleDelete',
        label: 'Auto Moderation Rule Delete',
        description: 'Auto Moderation rule was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'automod',
        event: 'autoModerationActionExecution',
        label: 'Auto Moderation Action Execution',
        description:
            'Auto Moderation rule was triggered and an action was executed.',
      ),
      WorkflowEventDefinition(
        category: 'channels',
        event: 'channelCreate',
        label: 'Channel Create',
        description: 'New guild channel created.',
      ),
      WorkflowEventDefinition(
        category: 'channels',
        event: 'channelUpdate',
        label: 'Channel Update',
        description: 'Channel was updated.',
      ),
      WorkflowEventDefinition(
        category: 'channels',
        event: 'channelDelete',
        label: 'Channel Delete',
        description: 'Channel was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'channels',
        event: 'channelPinsUpdate',
        label: 'Channel Pins Update',
        description: 'Message was pinned or unpinned.',
      ),
      WorkflowEventDefinition(
        category: 'threads',
        event: 'threadCreate',
        label: 'Thread Create',
        description:
            'Thread created, also sent when being added to a private thread.',
      ),
      WorkflowEventDefinition(
        category: 'threads',
        event: 'threadUpdate',
        label: 'Thread Update',
        description: 'Thread was updated.',
      ),
      WorkflowEventDefinition(
        category: 'threads',
        event: 'threadDelete',
        label: 'Thread Delete',
        description: 'Thread was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'threads',
        event: 'threadListSync',
        label: 'Thread List Sync',
        description:
            'Sent when gaining access to a channel, contains all active threads in that channel.',
      ),
      WorkflowEventDefinition(
        category: 'threads',
        event: 'threadMemberUpdate',
        label: 'Thread Member Update',
        description: 'Thread member for the current user was updated.',
      ),
      WorkflowEventDefinition(
        category: 'threads',
        event: 'threadMembersUpdate',
        label: 'Thread Members Update',
        description: 'Some users were added to or removed from a thread.',
      ),
      WorkflowEventDefinition(
        category: 'entitlements',
        event: 'entitlementCreate',
        label: 'Entitlement Create',
        description: 'Entitlement was created.',
      ),
      WorkflowEventDefinition(
        category: 'entitlements',
        event: 'entitlementUpdate',
        label: 'Entitlement Update',
        description: 'Entitlement was updated or renewed.',
      ),
      WorkflowEventDefinition(
        category: 'entitlements',
        event: 'entitlementDelete',
        label: 'Entitlement Delete',
        description: 'Entitlement was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'guilds',
        event: 'guildCreate',
        label: 'Guild Create',
        description: 'Guild became available, or the bot joined a guild.',
      ),
      WorkflowEventDefinition(
        category: 'guilds',
        event: 'guildUpdate',
        label: 'Guild Update',
        description: 'Guild was updated.',
      ),
      WorkflowEventDefinition(
        category: 'guilds',
        event: 'guildDelete',
        label: 'Guild Delete',
        description: 'Guild became unavailable, or the bot left a guild.',
      ),
      WorkflowEventDefinition(
        category: 'guilds',
        event: 'guildAuditLogCreate',
        label: 'Guild Audit Log Entry Create',
        description: 'A guild audit log entry was created.',
      ),
      WorkflowEventDefinition(
        category: 'guilds',
        event: 'guildEmojisUpdate',
        label: 'Guild Emojis Update',
        description: 'Guild emojis were updated.',
      ),
      WorkflowEventDefinition(
        category: 'guilds',
        event: 'guildStickersUpdate',
        label: 'Guild Stickers Update',
        description: 'Guild stickers were updated.',
      ),
      WorkflowEventDefinition(
        category: 'guilds',
        event: 'guildIntegrationsUpdate',
        label: 'Guild Integrations Update',
        description: 'Guild integration was updated.',
      ),
      WorkflowEventDefinition(
        category: 'guilds',
        event: 'guildMembersChunk',
        label: 'Guild Members Chunk',
        description: 'Response to Request Guild Members.',
      ),
      WorkflowEventDefinition(
        category: 'members',
        event: 'guildBanAdd',
        label: 'Guild Ban Add',
        description: 'User was banned from a guild.',
      ),
      WorkflowEventDefinition(
        category: 'members',
        event: 'guildBanRemove',
        label: 'Guild Ban Remove',
        description: 'User was unbanned from a guild.',
      ),
      WorkflowEventDefinition(
        category: 'members',
        event: 'guildMemberAdd',
        label: 'Guild Member Add',
        description: 'New user joined a guild.',
      ),
      WorkflowEventDefinition(
        category: 'members',
        event: 'guildMemberRemove',
        label: 'Guild Member Remove',
        description: 'User was removed from a guild.',
      ),
      WorkflowEventDefinition(
        category: 'members',
        event: 'guildMemberUpdate',
        label: 'Guild Member Update',
        description: 'Guild member was updated.',
      ),
      WorkflowEventDefinition(
        category: 'roles',
        event: 'guildRoleCreate',
        label: 'Guild Role Create',
        description: 'Guild role was created.',
      ),
      WorkflowEventDefinition(
        category: 'roles',
        event: 'guildRoleUpdate',
        label: 'Guild Role Update',
        description: 'Guild role was updated.',
      ),
      WorkflowEventDefinition(
        category: 'roles',
        event: 'guildRoleDelete',
        label: 'Guild Role Delete',
        description: 'Guild role was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'scheduled',
        event: 'guildScheduledEventCreate',
        label: 'Guild Scheduled Event Create',
        description: 'Guild scheduled event was created.',
      ),
      WorkflowEventDefinition(
        category: 'scheduled',
        event: 'guildScheduledEventUpdate',
        label: 'Guild Scheduled Event Update',
        description: 'Guild scheduled event was updated.',
      ),
      WorkflowEventDefinition(
        category: 'scheduled',
        event: 'guildScheduledEventDelete',
        label: 'Guild Scheduled Event Delete',
        description: 'Guild scheduled event was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'scheduled',
        event: 'guildScheduledEventUserAdd',
        label: 'Guild Scheduled Event User Add',
        description: 'User subscribed to a guild scheduled event.',
      ),
      WorkflowEventDefinition(
        category: 'scheduled',
        event: 'guildScheduledEventUserRemove',
        label: 'Guild Scheduled Event User Remove',
        description: 'User unsubscribed from a guild scheduled event.',
      ),
      WorkflowEventDefinition(
        category: 'integrations',
        event: 'integrationCreate',
        label: 'Integration Create',
        description: 'Guild integration was created.',
      ),
      WorkflowEventDefinition(
        category: 'integrations',
        event: 'integrationUpdate',
        label: 'Integration Update',
        description: 'Guild integration was updated.',
      ),
      WorkflowEventDefinition(
        category: 'integrations',
        event: 'integrationDelete',
        label: 'Integration Delete',
        description: 'Guild integration was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'invites',
        event: 'inviteCreate',
        label: 'Invite Create',
        description: 'Invite to a channel was created.',
      ),
      WorkflowEventDefinition(
        category: 'invites',
        event: 'inviteDelete',
        label: 'Invite Delete',
        description: 'Invite to a channel was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'messages',
        event: 'messageCreate',
        label: 'Message Create',
        description: 'Message was created.',
      ),
      WorkflowEventDefinition(
        category: 'messages',
        event: 'messageUpdate',
        label: 'Message Update',
        description: 'Message was edited.',
      ),
      WorkflowEventDefinition(
        category: 'messages',
        event: 'messageDelete',
        label: 'Message Delete',
        description: 'Message was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'messages',
        event: 'messageBulkDelete',
        label: 'Message Delete Bulk',
        description: 'Multiple messages were deleted at once.',
      ),
      WorkflowEventDefinition(
        category: 'reactions',
        event: 'messageReactionAdd',
        label: 'Message Reaction Add',
        description: 'User reacted to a message.',
      ),
      WorkflowEventDefinition(
        category: 'reactions',
        event: 'messageReactionRemove',
        label: 'Message Reaction Remove',
        description: 'User removed a reaction from a message.',
      ),
      WorkflowEventDefinition(
        category: 'reactions',
        event: 'messageReactionRemoveAll',
        label: 'Message Reaction Remove All',
        description: 'All reactions were explicitly removed from a message.',
      ),
      WorkflowEventDefinition(
        category: 'reactions',
        event: 'messageReactionRemoveEmoji',
        label: 'Message Reaction Remove Emoji',
        description:
            'All reactions for a given emoji were explicitly removed from a message.',
      ),
      WorkflowEventDefinition(
        category: 'reactions',
        event: 'messagePollVoteAdd',
        label: 'Message Poll Vote Add',
        description: 'User voted on a poll.',
      ),
      WorkflowEventDefinition(
        category: 'reactions',
        event: 'messagePollVoteRemove',
        label: 'Message Poll Vote Remove',
        description: 'User removed a vote on a poll.',
      ),
      WorkflowEventDefinition(
        category: 'presence',
        event: 'presenceUpdate',
        label: 'Presence Update',
        description: 'User presence was updated.',
      ),
      WorkflowEventDefinition(
        category: 'presence',
        event: 'typingStart',
        label: 'Typing Start',
        description: 'User started typing in a channel.',
      ),
      WorkflowEventDefinition(
        category: 'presence',
        event: 'userUpdate',
        label: 'User Update',
        description: 'Properties about the user changed.',
      ),
      WorkflowEventDefinition(
        category: 'stages',
        event: 'stageInstanceCreate',
        label: 'Stage Instance Create',
        description: 'Stage instance was created.',
      ),
      WorkflowEventDefinition(
        category: 'stages',
        event: 'stageInstanceUpdate',
        label: 'Stage Instance Update',
        description: 'Stage instance was updated.',
      ),
      WorkflowEventDefinition(
        category: 'stages',
        event: 'stageInstanceDelete',
        label: 'Stage Instance Delete',
        description: 'Stage instance was deleted or closed.',
      ),
      WorkflowEventDefinition(
        category: 'voice',
        event: 'voiceStateUpdate',
        label: 'Voice State Update',
        description: 'Someone joined, left, or moved a voice channel.',
      ),
      WorkflowEventDefinition(
        category: 'voice',
        event: 'voiceServerUpdate',
        label: 'Voice Server Update',
        description: 'Guild voice server was updated.',
      ),
      WorkflowEventDefinition(
        category: 'voice',
        event: 'voiceChannelEffectSend',
        label: 'Voice Channel Effect Send',
        description: 'Someone sent an effect in a connected voice channel.',
      ),
      WorkflowEventDefinition(
        category: 'webhooks',
        event: 'webhooksUpdate',
        label: 'Webhooks Update',
        description: 'Guild channel webhook was created, updated, or deleted.',
      ),
      WorkflowEventDefinition(
        category: 'soundboard',
        event: 'soundboardSoundCreate',
        label: 'Guild Soundboard Sound Create',
        description: 'Guild soundboard sound was created.',
      ),
      WorkflowEventDefinition(
        category: 'soundboard',
        event: 'soundboardSoundUpdate',
        label: 'Guild Soundboard Sound Update',
        description: 'Guild soundboard sound was updated.',
      ),
      WorkflowEventDefinition(
        category: 'soundboard',
        event: 'soundboardSoundDelete',
        label: 'Guild Soundboard Sound Delete',
        description: 'Guild soundboard sound was deleted.',
      ),
      WorkflowEventDefinition(
        category: 'soundboard',
        event: 'soundboardSoundsUpdate',
        label: 'Guild Soundboard Sounds Update',
        description: 'Guild soundboard sounds were updated.',
      ),
    ];
  }
}
